apiVersion: v1
kind: Service
metadata:
  labels:
    app: failedapp
    env: dev
    package: kcc
    provisioned_by: cli
  name: failedapp
  namespace: ecp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: failedapp
    env: dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: failedapp
    env: dev
    package: manual
    provisioned_by: cli
  name: failedapp
  namespace: ecp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failedapp
      env: dev
  template:
    metadata:
      labels:
        app: failedapp
        env: dev
        package: manual
        provisioned_by: cli
    spec:
      containers:
        - name: failedapp
          image: docker.io/jaichenchlani/failedapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 10m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 32Mi